swagger: "2.0"
info:
    title: Runner Server
    description: Credimi runner server API.
    version: "1.0"
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /fetch-apk-and-action:
        post:
            tags:
                - runner
            summary: fetch_apk_and_action runner
            operationId: runner#fetch_apk_and_action
            parameters:
                - name: fetch_apk_and_action_request_body
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/RunnerFetchApkAndActionRequestBody'
                    required:
                        - instance_url
                        - version_identifier
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/Fetchapkandactionresult'
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/RunnerFetchApkAndActionBadRequestResponseBody'
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/RunnerFetchApkAndActionUnauthorizedResponseBody'
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/RunnerFetchApkAndActionInternalErrorResponseBody'
                "502":
                    description: Bad Gateway response.
                    schema:
                        $ref: '#/definitions/RunnerFetchApkAndActionBadGatewayResponseBody'
            schemes:
                - http
    /process/:
        post:
            tags:
                - runner
            summary: process_start_missing runner
            operationId: runner#process_start_missing
            responses:
                "204":
                    description: No Content response.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/RunnerProcessStartMissingBadRequestResponseBody'
            schemes:
                - http
    /process/{namespace}:
        post:
            tags:
                - runner
            summary: process_start runner
            operationId: runner#process_start
            parameters:
                - name: namespace
                  in: path
                  required: true
                  type: string
                - name: object
                  in: body
                  required: true
                  schema:
                    type: object
                    properties:
                        old_namespace:
                            type: string
                            example: Corporis iste.
            responses:
                "202":
                    description: Accepted response.
                    schema:
                        $ref: '#/definitions/Processstartresult'
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/RunnerProcessStartBadRequestResponseBody'
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/RunnerProcessStartInternalErrorResponseBody'
            schemes:
                - http
    /process/list:
        get:
            tags:
                - runner
            summary: process_list runner
            operationId: runner#process_list
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            type: string
                            example: Nisi ut veniam asperiores ipsa saepe.
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/RunnerProcessListInternalErrorResponseBody'
            schemes:
                - http
    /store-pipeline-result:
        post:
            tags:
                - runner
            summary: store_pipeline_result runner
            operationId: runner#store_pipeline_result
            parameters:
                - name: store_pipeline_result_request_body
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/RunnerStorePipelineResultRequestBody'
                    required:
                        - instance_url
                        - run_identifier
            responses:
                "200":
                    description: OK response.
                    schema: {}
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/RunnerStorePipelineResultBadRequestResponseBody'
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/RunnerStorePipelineResultUnauthorizedResponseBody'
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/RunnerStorePipelineResultInternalErrorResponseBody'
                "502":
                    description: Bad Gateway response.
                    schema:
                        $ref: '#/definitions/RunnerStorePipelineResultBadGatewayResponseBody'
            schemes:
                - http
    /touch-fingerprint:
        get:
            tags:
                - runner
            summary: touch_fingerprint runner
            operationId: runner#touch_fingerprint
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/Touchfingerprintresult'
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/RunnerTouchFingerprintInternalErrorResponseBody'
            schemes:
                - http
definitions:
    Fetchapkandactionresult:
        title: 'Mediatype identifier: fetchapkandactionresult; view=default'
        type: object
        properties:
            apk_path:
                type: string
                example: Accusamus dolorum aut sed quas.
            code:
                type: string
                example: Quo qui at vel sint.
            version_id:
                type: string
                example: Fugiat maxime non sunt.
        description: fetch_apk_and_action_response_body result type (default view)
        example:
            apk_path: Reiciendis nostrum aut repellendus veniam voluptatem.
            code: Hic molestias eaque consectetur.
            version_id: Ipsa dolor blanditiis repudiandae.
        required:
            - apk_path
            - version_id
    Processstartresult:
        title: 'Mediatype identifier: processstartresult; view=default'
        type: object
        properties:
            namespace:
                type: string
                example: Quas animi.
            status:
                type: string
                example: Ut similique quidem.
        description: process_start_response_body result type (default view)
        example:
            namespace: Tempore dolorum voluptatem.
            status: Quis voluptatem pariatur voluptas sapiente id voluptatem.
        required:
            - status
            - namespace
    RunnerFetchApkAndActionBadGatewayResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: fetch_apk_and_action_bad_gateway_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    RunnerFetchApkAndActionBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: fetch_apk_and_action_bad_request_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    RunnerFetchApkAndActionInternalErrorResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: fetch_apk_and_action_internal_error_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    RunnerFetchApkAndActionRequestBody:
        title: RunnerFetchApkAndActionRequestBody
        type: object
        properties:
            action_identifier:
                type: string
                example: Eaque aut corporis velit voluptatem ipsa nihil.
            instance_url:
                type: string
                example: Et ut quia.
            version_identifier:
                type: string
                example: Natus veritatis laudantium sequi accusantium omnis et.
        example:
            action_identifier: Sit et.
            instance_url: Omnis accusamus esse est quasi.
            version_identifier: Quaerat quisquam sunt eveniet nulla odio odit.
        required:
            - instance_url
            - version_identifier
    RunnerFetchApkAndActionUnauthorizedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: fetch_apk_and_action_unauthorized_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    RunnerProcessListInternalErrorResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: process_list_internal_error_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    RunnerProcessStartBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: process_start_bad_request_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    RunnerProcessStartInternalErrorResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: process_start_internal_error_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    RunnerProcessStartMissingBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: process_start_missing_bad_request_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    RunnerStorePipelineResultBadGatewayResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: store_pipeline_result_bad_gateway_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    RunnerStorePipelineResultBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: store_pipeline_result_bad_request_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    RunnerStorePipelineResultInternalErrorResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: store_pipeline_result_internal_error_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    RunnerStorePipelineResultRequestBody:
        title: RunnerStorePipelineResultRequestBody
        type: object
        properties:
            instance_url:
                type: string
                example: Aliquam sed a hic ut.
            last_frame_path:
                type: string
                example: Maiores voluptatem accusantium placeat et maiores omnis.
            logcat_path:
                type: string
                example: Itaque placeat tenetur eaque ab illum reiciendis.
            run_identifier:
                type: string
                example: Est voluptatem incidunt et.
            runner_identifier:
                type: string
                example: Ipsa sint occaecati.
            video_path:
                type: string
                example: Ut cumque odit non officia eum.
        example:
            instance_url: Culpa sit nihil facilis.
            last_frame_path: Deleniti nobis consequatur.
            logcat_path: Quisquam dolorem porro expedita quam.
            run_identifier: Velit totam inventore.
            runner_identifier: Quos ut magni.
            video_path: Sit ut eos necessitatibus unde temporibus iure.
        required:
            - instance_url
            - run_identifier
    RunnerStorePipelineResultUnauthorizedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: store_pipeline_result_unauthorized_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    RunnerTouchFingerprintInternalErrorResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: touch_fingerprint_internal_error_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    Touchfingerprintresult:
        title: 'Mediatype identifier: touchfingerprintresult; view=default'
        type: object
        properties:
            status:
                type: string
                example: Molestiae aut eos.
        description: touch_fingerprint_response_body result type (default view)
        example:
            status: Inventore voluptates.
        required:
            - status
